### ISSUE TITLE
Enable patch in Shop class

### ISSUE THREAD

**Issue by bklein1** [basklei92/epages-rest-java#1]
The Jersey library does not provide a way to use the HTTP method patch. Unfortunately the ePages REST API uses patch (e.g. for changing a Product). There are three possibilities to resolve this problem:

1. There is a hack where you can modify a post as patch.
2. Use the Apache library
3. Build our own HTTP methods by using the java native libraries

**Comment by basklei92** [comment]
Patch is working now.
